Fix UndefVarError: sources not defined
The `sources` variable does not exist. Apparently it was replaced by `raygenerator` (?)

```
ERROR: UndefVarError: sources not defined
Stacktrace:
 [1] trace(system::CSGOpticalSystem{Float64, Float32, Ellipse{Float64}, LensAssembly}, raygenerator::UniformOpticalSource{Float64, RandomGaussianOriginPoints{Float64}, RandomSource{Float64, RandomGaussianOriginPoints{Float64}}}; printprog::Bool, test::Bool, outpath::Nothing)
   @ OpticSim ~/.julia/packages/OpticSim/4qItW/src/Optical/OpticalSystem.jl:353
```